# Generated by Django 5.1.5 on 2025-01-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0002_remove_thread_board_remove_post_thread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
