# Generated by Django 5.1.5 on 2025-01-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='board',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='message',
        ),
        migrations.AddField(
            model_name='post',
            name='micropost',
            field=models.CharField(blank=True, max_length=140, verbose_name='tweet'),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='Unnamed', max_length=15, verbose_name='user name'),
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
