# Generated by Django 5.1.5 on 2025-02-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0002_thread_author_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
