# Generated by Django 5.1.5 on 2025-06-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0007_usernoticestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タスク名')),
                ('due_date', models.DateField(verbose_name='締切日')),
                ('grade', models.IntegerField(choices=[(1, '1年'), (2, '2年'), (3, '3年'), (4, '4年')], verbose_name='学年')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
